# Generated by Django 5.2.1 on 2025-06-21 20:39

import core.models
import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250530_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(db_column='created_at', default=core.models.TimestampedModel.current_timestamp)),
                ('updated_at', models.IntegerField(db_column='updated_at', default=core.models.TimestampedModel.current_timestamp)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('deleted_at', models.IntegerField(blank=True, db_column='deleted_at', null=True)),
                ('detail', models.JSONField(db_column='detail', null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
