# Generated by Django 4.2.7 on 2025-06-27 12:12

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_trainingvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(db_column='created_at', default=core.models.TimestampedModel.current_timestamp)),
                ('updated_at', models.IntegerField(db_column='updated_at', default=core.models.TimestampedModel.current_timestamp)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('deleted_at', models.IntegerField(blank=True, db_column='deleted_at', null=True)),
                ('detail', models.JSONField(db_column='detail', null=True)),
                ('final_prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('total_frames_processed', models.IntegerField()),
                ('frames_with_wrist_data', models.IntegerField()),
                ('final_wrist_angle', models.FloatField(blank=True, null=True)),
                ('average_wrist_angle', models.FloatField(blank=True, null=True)),
                ('average_speed', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('form_quality', models.FloatField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='accounts.athlete')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='deleted_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AthletePerformance',
            },
        ),
    ]
