# Generated by Django 4.2.7 on 2025-06-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_athleteperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingvideo',
            name='team',
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.athlete'),
        ),
    ]
